/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'

export default function Home() {

  let hero_Description = ' We believe that every person deserves the opportunity to live a life of dignity and purpose, and it is our goal to help make this a reality for as many people as possible.'

  return (
    <>
      <Head>
        <title>ENHANCE INDIA FOUNDATION CHARITABLE TRUST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='hero'>
        <div className='hero_Content_Container'>
          <div className='hero_Content'>
              <div className="hero_Title">
                <p>
                  Empower <span className='green'>Change</span> and Transform <span className='green'>Lives</span>
                </p>
              </div>
              <div className="hero_Description">
                <p>
                  { hero_Description }
                </p>
              </div>
          </div>
        </div>
      </main>
      {/* hero ------ */}
      {/* LOGO DESCRIBE */}
    </>
  )
}
